# Generated by Django 4.2.6 on 2023-11-20 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User')], default=2, null=True),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('commonfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.commonfield')),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('car_name', models.CharField(blank=True, max_length=255, null=True)),
                ('car_type', models.CharField(blank=True, choices=[(1, 'Petrol'), (2, 'Deisel'), (2, 'CNG')], max_length=50, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comapany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.commonfield',),
        ),
    ]
