# Generated by Django 4.2.6 on 2023-11-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.PositiveIntegerField(blank=True, choices=[('petrol', 'petrol'), ('deisel', 'deisel'), ('cng', 'cng')], max_length=50, null=True),
        ),
    ]
